# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='pub_date',
        ),
    ]
