# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_remove_initiative_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 14, 13, 10, 51942, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initiative',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 14, 13, 19, 16092, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 14, 13, 36, 88332, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 14, 13, 47, 484384, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
